set -x

export VLLM_ATTENTION_BACKEND=XFORMERS
export VLLM_ASCEND_ENABLE_NZ=0

BASE_PATH='/home/ma-user/work'
MODEL_PATH='/home/ma-user/work/model/qwen3-0.6B/main'

python3 -m verl.trainer.main_ppo \
algorithm.adv_estimator=gpo \
data.train_files="$BASE_PATH/dataset/xyi/train.json" \
data.val_files="$BASE_PATH/dataset/xyi/val_high_pass.json","$BASE_PATH/dataset/xyi/val_low_pass.json" \
data.prompt_key=prompt \
data.reward_key=data_source \
data.return_raw_chat=true \
reward.custom_reward_function.path="$BASE_PATH/rewards/xyi/reward_math_verifier.py" \
reward.custom_reward_function.name=compute_score \
reward.reward_model.enable=False \
data.train.batch_size=32 \
data.max_prompt_length=1024 \
data.max_response_length=2048 \
data.filter_overlong_prompts=True \
data.truncation='error' \
actor_rollout_ref.model.path=$MODEL_PATH \
actor_rollout_ref.actor.optim.lr=1e-7 \
actor_rollout_ref.model.use_remove_padding=False \
actor_rollout_ref.actor.entropy_coeff=0.001 \
actor_rollout_ref.actor.ppo_mini_batch_size=16 \
actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
actor_rollout_ref.actor.use_kl_loss=True \
actor_rollout_ref.actor.kl_loss_coef=0.001 \
actor_rollout_ref.actor.kl_loss_type=low_var_kl \
actor_rollout_ref.actor.clip_ratio_high=0.20 \
actor_rollout_ref.model.enable_gradient_checkpointing=True \
actor_rollout_ref.actor.fsdp_config.param_offload=False \
actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
actor_rollout_ref.rollout.enable_chunked_prefill=False \
actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
actor_rollout_ref.rollout.agent.num_workers=2 \
actor_rollout_ref.rollout.name=vllm \
actor_rollout_ref.rollout.mode=async \
actor_rollout_ref.rollout.gpu_memory_utilization=0.32 \
actor_rollout_ref.rollout.n=8 \
actor_rollout_ref.rollout.response_length=2048 \
actor_rollout_ref.rollout.agent.default_agent_loop=entropy_branch_agent \
actor_rollout_ref.rollout.custom.entropy_branch.initial_samples=4 \
actor_rollout_ref.rollout.custom.entropy_branch.branch_samples=4 \
actor_rollout_ref.rollout.custom.entropy_branch.position_top_k=8 \
actor_rollout_ref.rollout.custom.entropy_branch.branch_selection=uniform \
actor_rollout_ref.rollout.custom.entropy_branch.vocab_top_m=32 \
actor_rollout_ref.rollout.custom.entropy_branch.min_prefix_tokens=4 \
actor_rollout_ref.rollout.custom.entropy_branch.min_suffix_tokens=32 \
actor_rollout_ref.rollout.custom.entropy_branch.debug_print_second_pass=False \
actor_rollout_ref.rollout.val_kwargs.n=4 \
actor_rollout_ref.rollout.val_kwargs.do_sample=True \
actor_rollout_ref.rollout.val_kwargs.temperature=0.7 \
actor_rollout_ref.rollout.enforce_eager=True \
actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
actor_rollout_ref.rollout.fsdp_config.param_offload=False \
algorithm.kl_ctrl.kl_coef=0.001 \
trainer.critic.warmup=0 \
trainer.logger=['console','tensorboard'] \
trainer.project_name='verl_090_math_xyi_qwen3_06b' \
trainer.experiment_name='CURE' \
trainer.n_gpus_per_node=4 \
trainer.val_before_train=False \
trainer.nodes=1 \
trainer.save_freq=180 \
trainer.test_freq=8 \
trainer.total_epochs=10